### ISSUE TITLE
Error: illegal mode: lose input

### ISSUE THREAD

**Issue by mryndzionek** [tsnlab/connx#87]
While converting an ONNX model I have:
```
Fatal: Cannot import onnx model, got exception from ONNX: illegal mode: lose input onnx::Concat_296
````

I think it has something to do with the Identity operator. Help with solving this is greatly appreciated.

**Comment by semihlab** [comment]
Which onnx version did you imported? CONNX supports from 1.5 to 1.11. The latest verion is working in progress.

**Comment by mryndzionek** [comment]
Okay, fair enough. The version I used is 1.12.0.

**Comment by mryndzionek** [comment]
I converted to 1.11, but still same error.

**Comment by tribela** [comment]
If you don't mind, Please provide these info:

- The model you used
- The command you run
- Stack trace if available
- Version(commit hash) of onnx-connx and connx

**Comment by mryndzionek** [comment]
I'm really sorry, I think I've sent the wrong error message (from another ONNX compiler). I was testing many  compilers/converters in last few weeks, but actually none of them was able to convert/compile my model, so I'm attaching the model:
[model_1.onnx.tar.gz](https://github.com/tsnlab/connx/files/10023036/model_1.onnx.tar.gz)
I think the main problem is that, as Netron is showing, the Identity layers are unconnected. Let me know if you have more insight.
